version: "3.3"

services:
  frontend:
    build:
      context: ./frontend/biblioteca-app
      dockerfile: Dockerfile
    ports:
      - "90:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/biblioteca-app:/app:cached
      - /app/node_modules
    stdin_open: true
    tty: true

  libro:
    build:
      context: ./backend/libro
    ports:
      - "8001:8000"
    environment:
      DB_HOST: database-2.cbekimjprojv.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_USER: admin2
      DB_PASS: CC-utec_2024-s3
      DB_NAME: bd_api_libro

  prestamo:
    build:
      context: ./backend/prestamo
    ports:
      - "8002:8000"
    environment:
      DB_HOST: database-2.cbekimjprojv.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_USER: admin2
      DB_PASS: CC-utec_2024-s3
      DB_NAME: bd_api_prestamo

  usuario:
    build:
      context: ./backend/usuario
    ports:
      - "8003:8000"
    environment:
      DB_HOST: database-2.cbekimjprojv.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_USER: admin2
      DB_PASS: CC-utec_2024-s3
      DB_NAME: bd_api_usuario


